### ISSUE TITLE
Support external routers

### ISSUE THREAD

**Issue by jmikrut** [trbldesign/react-modal#1]
Currently, `react-modal` uses `window.history.pushState` to update the window location query.

This is not picked up on by React Router or NextJS' Router, so those tools are unable to pick up on the change and don't track the activity of the modal doing its thing.

I have some ideas for how this should be implemented in practice.

**Comment by jacobsfletch** [comment]
@jmikrut There's already a `resetInternalState` method on the `ModalProvider` that -- if exposed to the context -- will do exactly what you're describing. Aliasing this method for easier consumption may be a good idea, too.
